### ISSUE TITLE
[GetToken] GetToken failed with status code: NeedPermission for GameServices Sign in 

### ISSUE THREAD

**Issue by jennycxu** [myflashlab/GameServices-ANE#28]
## Environment ##
* Android API Version: 26
* iOS Version: N/A 
* AIR SDK Version: 29.0.0.122

## Problem Description ##
When I try to use silentSignIn() using the new Google Sign in ANE with GameServices-ANE, I get the following error: 
```W/Conscrypt(11545): Could not set socket write timeout: java.lang.reflect.InvocationTargetException
W/Conscrypt(11545): 	at java.lang.reflect.Method.invoke(Native Method)
W/Conscrypt(11545): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/Conscrypt(11545): Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file number)
W/Conscrypt(11545): 	at libcore.io.Posix.setsockoptTimeval(Native Method)
W/Conscrypt(11545): 	at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:147)
W/Conscrypt(11545): Could not set socket write timeout: java.lang.reflect.InvocationTargetException
W/Conscrypt(11545): 	at java.lang.reflect.Method.invoke(Native Method)
W/Conscrypt(11545): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/Conscrypt(11545): Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file number)
W/Conscrypt(11545): 	at libcore.io.Posix.setsockoptTimeval(Native Method)
W/Conscrypt(11545): 	at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:147)
W/Auth    (11545): [GetToken] GetToken failed with status code: NeedPermission
D/ActivityManager( 3168): bindService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms, action: null
W/Auth    (12696): [GoogleAuthUtil] GoogleAuthUtil
W/GamesServiceBroker(12696): Client connected with SDK 13004000, Services 12685009, and Games 59040038
W/GamesServiceBroker(12696): Client connected with SDK 13004000, Services 12685009, and Games 59040038
```  

And the app doesn't let me sign the user in. I wasn't very sure why this was happening and I double checked to make sure that the client ID used and the SHA1 fingerprint matched what was in the Google API Console and was in the Linked Google Play Services in the Developers Console. Thanks! 

* Copy your manifest ```.xml``` file.
```xml
 <manifest android:installLocation="auto">
            <uses-sdk android:minSdkVersion="11" android:targetSdkVersion="26" />
            
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            
            <supports-screens
            android:resizeable="true"
            android:smallScreens="true"
            android:largeScreens="true"
            android:xlargeScreens="true"
            android:normalScreens="true"
            android:anyDensity="true"/>
            <!--
            Required by firebase_iid.ane
            Change "air.com.doitflash.firebaseCore" to your own app package name
            -->
            <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
            <permission android:name="air.com.jcsoft.canyouescapeheartbreak.permission.C2D_MESSAGE" android:protectionLevel="signature" />
            <uses-permission android:name="air.com.jcsoft.canyouescapeheartbreak.permission.C2D_MESSAGE" />
            
            <application android:hardwareAccelerated="true" android:name="android.support.multidex.MultiDexApplication">
            <activity android:launchMode="singleTop">
            <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <category android:name="android.intent.category.DEFAULT" />
            
            <!-- Change "air.com.doitflash.firebaseCore" to your own app package name -->
            <data android:scheme="air.com.jcsoft.canyouescapeheartbreak" />
            </intent-filter>
            </activity>
            <!--
            Required by the firebase_common.ane
            Change "air.com.doitflash.firebaseCore" to your own app package name
            -->
            <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.com.jcsoft.canyouescapeheartbreak.live.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />
            <service
            android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService"
            android:exported="true">
            <intent-filter>
            <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
            </service>
            
            <activity
            android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:excludeFromRecents="true" android:exported="false"/>
            
            <service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
            android:exported="true"
            android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>
            
            <!-- Required by the googlePlayServices_basement.ane -->
            <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
            
            <!--
            Required by firebase_iid.ane
            Change "air.com.doitflash.firebaseCore" to your own app package name
            -->
            <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <category android:name="air.com.jcsoft.canyouescapeheartbreak" />
            </intent-filter>
            </receiver>
            
            <!-- Required by firebase_analyticsImpl.ane and firebase-analytics.ane -->
            <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
            android:enabled="true"
            android:exported="false">
            </receiver>
            <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
            android:permission="android.permission.INSTALL_PACKAGES"
            android:enabled="true">
            <intent-filter>
            <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>
            </receiver>
            <service
            android:name="com.google.android.gms.measurement.AppMeasurementService"
            android:enabled="true"
            android:exported="false"/>
            
            <service
            android:name="com.google.android.gms.measurement.AppMeasurementJobService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:enabled="true"
            android:exported="false"/>
            <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
            <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
            </service>
            <!-- Required by googlePlayServices_base.ane -->
            <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:exported="false"/>
            <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 980654517658"/>
            
            
            <activity android:name="com.jirbo.adcolony.AdColonyOverlay" android:windowSoftInputMode="adjustNothing" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
            <activity android:name="com.jirbo.adcolony.AdColonyFullscreen" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />
            <activity android:name="com.jirbo.adcolony.AdColonyBrowser" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />
            
            <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
            </application>
```
* Copy your Actionscript code.
```actionscript
// initialize the Firebase as early as possible in your project
var isConfigFound:Boolean = Firebase.init();
var isAnalyticsSupported:Boolean = isConfigFound;
FirebaseAnalytics.init();

// depending on your app design, you must customize the Signin Options
// If you want GoogleGames signin only, do like below:
var options:GSignInOptions = new GSignInOptions();
options.gamesSignIn = true; // set to true if you are working with Google Games Services ANE.

// you don't want to bother users with a permission page, right? so set these to false 
// and don't ask for extra access scopes.
options.requestId = false;
options.requestProfile = false;
options.requestEmail = false;

// IMPORTANT: if you are not using Game Save Snapshots, you would not need GScopes.DRIVE_APPFOLDER
options.requestScopes = [
	"https://www.googleapis.com/auth/games" // must be set for games
];

// then pass the options to the initialization method of the GSignIn ANE
GSignIn.init(options);

// Finally, add listeners
GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSigninSuccess);
GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSigninFailure);
GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSigninSuccess);
GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSigninFailure);
GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_SUCCESS, onSignoutSuccess);
GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_FAILURE, onSignoutFailure);

// check if user is already loggedin or not
var account:GAccount = GSignIn.signedInAccount;
if(account)
{
	initGames(); // here, you will initialize the GameServices ANE
}
else
{
	// You should first check if user can signin silently, if she can't, use the signin() method
	GSignIn.silentSignIn();
}

function onSigninSuccess(e:GSignInEvents):void
{
	trace("e.account.scopes: "+ e.account.scopes);
	initGames();
}

function onSilentSigninSuccess(e:GSignInEvents):void
{
	initGames();
}function onSilentSigninFailure(e:GSignInEvents):void
{
	/*
		check the meaning of failure code here:
		https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes
		https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
	 */
	trace("onSilentSigninFailure: " + e.msg);
}
function onSigninFailure(e:GSignInEvents):void
{
	trace("onSigninFailure: " + e.msg);
}
function onSignoutSuccess(e:GSignInEvents):void
{
	trace("onSignoutSuccess");
	Games.dismiss();
}
function onSignoutFailure(e:GSignInEvents):void
{
	trace("onSignoutFailure: " + e.msg);
}
function initGames():void
{
	Games.init();
	signInReady = true;
	if(!Games.listener.hasEventListener(GamesEvents.CONNECT_SUCCESS))
	{
		Games.listener.addEventListener(GamesEvents.CONNECT_SUCCESS, onConnectSuccess);
		Games.listener.addEventListener(GamesEvents.CONNECT_FAILURE, onConnectFailure);

		// There's no need to add this listener, it just shows you some more information about
		// how activities inside the ANE are doing.
		Games.listener.addEventListener(GamesEvents.ACTIVITY_RESULT_CODES, onActivityResultCodes);
	}
}


function onConnectFailure(e:GamesEvents):void
{
	trace("onConnectFailure: " + e.msg);
}

function onActivityResultCodes(e:GamesEvents):void
{
	// https://developers.google.com/android/reference/com/google/android/gms/games/GamesActivityResultCodes
	trace("onActivityResultCodes: " + e.status);
}

function onConnectSuccess(e:GamesEvents):void
{
	trace("displayName: " + e.player.displayName);
	trace("id: " + e.player.id);
	trace("lastPlayedTimestamp: " + e.player.lastPlayedTimestamp);
	trace("title: " + e.player.title);
	trace("retrievedTimestamp: " + e.player.retrievedTimestamp);
	trace("hasHiResImage: " + e.player.hasHiResImage);
	trace("hasIconImage: " + e.player.hasIconImage);

	if(e.player.levelInfo)
	{
		trace("levelInfo.currentXpTotal: " + e.player.levelInfo.currentXpTotal);
		trace("levelInfo.isMaxLevel: " + e.player.levelInfo.isMaxLevel);
		trace("levelInfo.lastLevelUpTimestamp: " + e.player.levelInfo.lastLevelUpTimestamp);
		
		trace("levelInfo.currentLevel.levelNumber: " + e.player.levelInfo.currentLevel.levelNumber);
		trace("levelInfo.currentLevel.maxXp: " + e.player.levelInfo.currentLevel.maxXp);
		trace("levelInfo.currentLevel.minXp: " + e.player.levelInfo.currentLevel.minXp);
		
		trace("levelInfo.nextLevel.levelNumber: " + e.player.levelInfo.nextLevel.levelNumber);
		trace("levelInfo.nextLevel.maxXp: " + e.player.levelInfo.nextLevel.maxXp);
		trace("levelInfo.nextLevel.minXp: " + e.player.levelInfo.nextLevel.minXp);
	}
}

if (isConfigFound)
{
	// If you wish to see the Firebase SDK debugging logs in detail, use the following
	Firebase.setLoggerLevel(FirebaseConfig.LOGGER_LEVEL_MAX);

	var config:FirebaseConfig = Firebase.getConfig();
	trace("default_web_client_id = " + 			config.default_web_client_id);
	trace("firebase_database_url = " + 			config.firebase_database_url);
	trace("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
	trace("google_api_key = " + 				config.google_api_key);
	trace("google_app_id = " + 					config.google_app_id);
	trace("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
	trace("google_storage_bucket = " + 			config.google_storage_bucket);
}
else
{
	trace("Config file is not found!");
}


if (!GSignIn.signedInAccount) {
			GSignIn.silentSignIn();
			stage.addEventListener(Event.ENTER_FRAME, checkReady);
		} else {
			Games.leaderboards.submitScore(LEADERBOARD_ID, bestScore, "ScoreTag", true);
			if(!Games.leaderboards.hasEventListener(GamesEvents.LEADERBOARDS_WINDOW_FAILURE))
Games.leaderboards.addEventListener(GamesEvents.LEADERBOARDS_WINDOW_FAILURE, onLeaderboardsWindowFailure);
			
			if(!Games.leaderboards.hasEventListener(GamesEvents.LEADERBOARDS_WINDOW_DISMISSED))
				Games.leaderboards.addEventListener(GamesEvents.LEADERBOARDS_WINDOW_DISMISSED, onLeaderboardsWindowDismissed);
			Games.leaderboards.showNativeWindow(LEADERBOARD_ID, Leaderboards.TIME_SPAN_ALL_TIME);
		}
```

## Steps to Reproduce ##
Simply calling silentSignIn() will make the error occur.

**Comment by myflashlab** [comment]
hmm, try adding ```<uses-permission android:name="android.permission.GET_ACCOUNTS" />``` and see what happens.

**Comment by jennycxu** [comment]
Hmm I get the same error even after adding this: 

`I/Finsky  (26741): [1] com.google.android.finsky.p2p.c.a(10): Frosting ID looked up on UI thread. Caller should move to a background thread.
W/GamesServiceBroker(16346): Client connected with SDK 13004000, Services 12685008, and Games 59040036
W/GamesServiceBroker(16346): Client connected with SDK 13004000, Services 12685008, and Games 59040036
W/GamesServiceBroker(16346): Client connected with SDK 13004000, Services 12685008, and Games 59040036
I/AsyncOpDispatcher(16346): 44-AuthAccountWithNoServerAuthCallback
I/Launcher(16160): Deferring update until onResume
I/Launcher( 1006): Deferring update until onResume
W/Auth    (16255): [GetToken] GetToken failed with status code: NeedPermission
I/Finsky  (28292): [1223] com.google.android.finsky.installer.r.b(109): User=UserHandle{10} released=com.google.android.apps.plus
W/Auth    (16346): [GoogleAuthUtil] GoogleAuthUtil
W/GamesServiceBroker(16346): Client connected with SDK 13004000, Services 12685008, and Games 59040036
W/GamesServiceBroker(16346): Client connected with SDK 13004000, Services 12685008, and Games 59040036
I/Finsky  (28292): [1] com.google.android.finsky.p2p.c.a(10): Frosting ID looked up on UI thread. Caller should move to a background thread.
I/ActivityManager(  540): Killing 27583:jp.co.omronsoft.iwnnime.ml/u10a79 (adj 15): empty #17
W/libprocessgroup(  540): failed to open /acct/uid_1010079/pid_27583/cgroup.procs: No such file or directory`

**Comment by myflashlab** [comment]
We don't seem to be able to duplicate the problem. it keeps on working fine. However, we did some Googling and found some results, for example this one: https://github.com/playgameservices/play-games-plugin-for-unity/issues/2178#issuecomment-384591835 see if you can relate?

**Comment by jennycxu** [comment]
Thanks! However, the game is already live on the app stores, and I made sure that the email was in the testing group so I'm still not sure why it was still not working. One thing I noticed was that the androidSupport version I was using was 26.0.2 while the new version is 27.0.2, do you know if something was updated in 27.0.2 that might affect this specific issue? Thanks again for your time.

**Comment by myflashlab** [comment]
There could be. Always try using the latest ANEs and latest dependency files. I would suggest if you first try to run things in a simple demo app, with the same package name and using the minimum code and see how it goes. usually testing in a simple demo app would help me locate the problem easier. There must be something missing now that you are upgrading to use the new sign-in flow... 🤔

**Comment by jennycxu** [comment]
It fixed it, thanks for your help! Thank you, the solution was upgrading to the new AIR SDK, using the new androidSupport, and using GSignIn.signIn() instead of silentSignIn()
