### ISSUE TITLE
4.1.0 loading achievements exception

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/GameServices-ANE#29]
## Environment ##
* Android Version:  7.0
* AIR Version: 30

## Problem Description ##
`Games.achievements.load(true);` - exception
```xml
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.crazyflasher.ktk</id>
  <versionNumber>1.3.0</versionNumber>
  <supportedProfiles>mobileDevice</supportedProfiles>
  <!--supportedProfiles>extendedDesktop</supportedProfiles-->
  <filename>Stickman Combats</filename>
  <name>
    <text xml:lang="en">Stickman Combats</text>
    <text xml:lang="ru">Stickman Combats</text>
  </name>
  <android>
    <containsVideo>true</containsVideo>
    <colorDepth>16bit</colorDepth>
    <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">

			  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="26"/>

              <!--for internal videos-->
              <uses-permission android:name="android.permission.WAKE_LOCK" />
	          <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
              <!--for internal videos-->

              <!--Admob, Billing, AirNetworkInfo-->
              <uses-permission android:name="android.permission.INTERNET"/>

              <!--Admob, AirNetworkInfo-->
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

              <!--AirNetworkInfo-->
              <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

              <!--Billing-->
              <uses-permission android:name="com.android.vending.BILLING" />

			  <uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch"/>

			  <application android:allowBackup="true" android:hardwareAccelerated="true" android:name="android.support.multidex.MultiDexApplication">

                <meta-data android:name="android.max_aspect" android:value="2.0" />

                <!--Game Services-->
                <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 531279289872"/>

                <!-- Billing -->
		        <activity android:name="com.doitflash.inAppBilling.utils.MyPurchase" android:theme="@style/Theme.Transparent" />

                <!--Admob-->
                <activity>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                    <intent-filter>
                        <action android:name="android.intent.action.VIEW" />
                        <category android:name="android.intent.category.BROWSABLE" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>

                <!-- Admob -->
                <activity
                  android:name="com.google.android.gms.ads.AdActivity"
                  android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
                  android:theme="@android:style/Theme.Translucent" />

                <!-- GoogleSignIn -->
                <activity
                  android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:excludeFromRecents="true" android:exported="false"/>

                <service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
                    android:exported="true"
                    android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>

                <activity
                    android:name="com.google.android.gms.common.api.GoogleApiActivity"
                    android:theme="@android:style/Theme.Translucent.NoTitleBar"
                    android:exported="false"/>

                <!-- GoogleSignIn, Admob -->
                <meta-data
			        android:name="com.google.android.gms.version"
			        android:value="@integer/google_play_services_version"/>

              </application>
			</manifest>

		]]></manifestAdditions>
    <disableMediaCodec>true</disableMediaCodec>
  </android>
  <iPhone>
  </iPhone>
  <initialWindow>
    <title>Stickman Combats</title>
    <content>kill-the-king.swf</content>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <autoOrients>true</autoOrients>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>direct</renderMode>
    <depthAndStencil>true</depthAndStencil>
    <softKeyboardBehavior>none</softKeyboardBehavior>
  </initialWindow>
  <icon>
             <image36x36>assets/icons/android/icon-36x36.png</image36x36>         <image48x48>assets/icons/android/icon-48x48.png</image48x48>         <image72x72>assets/icons/android/icon-72x72.png</image72x72>         <image96x96>assets/icons/android/icon-96x96.png</image96x96>         <image144x144>assets/icons/android/icon-144x144.png</image144x144>         <image192x192>assets/icons/android/icon-192x192.png</image192x192>     
  </icon>
  <description>
    <text xml:lang="ru"></text>
    <text xml:lang="en"></text>
  </description>
  <extensions>
    <extensionID>com.freshplanet.ane.AirNetworkInfo</extensionID>
    <extensionID>adobe.nativeExtension.dataShare</extensionID>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.gameServices</extensionID>

    <!--dependencies-->
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
  </extensions>
  <supportedLanguages>en ru</supportedLanguages>
</application>
```
```actionscript
/**
 * Created by CrazyFlasher on 8.05.2018.
 */
package com.crazyfm.devkit.gameServices
{
	import com.crazyfm.devkit.utils.PlatformUtils;
	import com.domwires.core.mvc.model.AbstractModel;
	import com.myflashlab.air.extensions.gSignIn.GAccount;
	import com.myflashlab.air.extensions.gSignIn.GScopes;
	import com.myflashlab.air.extensions.gSignIn.GSignIn;
	import com.myflashlab.air.extensions.gSignIn.GSignInEvents;
	import com.myflashlab.air.extensions.gSignIn.GSignInOptions;
	import com.myflashlab.air.extensions.googleGames.Achievement;
	import com.myflashlab.air.extensions.googleGames.Games;
	import com.myflashlab.air.extensions.googleGames.GamesEvents;

	import flash.filesystem.File;

	public class MyFlashLabsGameServicesModel extends AbstractModel implements IGameServicesModel
	{
		[Autowired(name="gameServicesModelEnabled")]
		public var _enabled:Boolean;

		[Autowired(name="gameServicesModelWebClientId", optional="true")]
		public var webClientId:String;

		private var _isPending:Boolean;
		private var _initialized:Boolean;
		private var _signedIn:Boolean;
		private var _userId:String;
		private var _nickname:String;
		private var _email:String;
		private var _serverAuthCode:String;

		private var _errorType:String = "Offline";
		private var _errorReason:String = "Cannot sign in. Probably you are offline.";

		private var achievementList:Array;

		[PostConstruct]
		public function init():void
		{
			if (_enabled && PlatformUtils.isMobile)
			{
				if (PlatformUtils.isAndroid)
				{
				   var options:GSignInOptions = new GSignInOptions();
				   options.gamesSignIn = true; // set to true if you are working with Google Games Services ANE.

//				   options.requestIdToken = webClientId; // get the client ID of your server
				   options.requestServerAuthCode = webClientId; // get the client ID of your server

				   options.requestId = true;
				   options.requestProfile = false;
				   options.requestEmail = false;

				   // IMPORTANT: if you are not using Game Save Snapshots, you would not need GScopes.DRIVE_APPFOLDER
				   options.requestScopes = [
					   GScopes.GAMES
				   ];

				   // and pass the object to the initialization method of the ANE
				   GSignIn.init(options);

				   // Then, add listeners
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSignInSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSignInFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_SUCCESS, onSignOutSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_FAILURE, onSignOutFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_SUCCESS, onRevokeAccessSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_FAILURE, onRevokeAccessFailure);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_SUCCESS, onRequestSuccess);
				   GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_FAILURE, onRequestFailure);

				   _initialized = true;
				}
			}
		}

		private function getAchievementById(id:String):Achievement
		{
			var ach:Achievement;
			for (var i:int = 0; i < achievementList.length; i++)
			{
				ach = achievementList[i];

				if (ach.id == id)
				{
					return ach;
				}
			}

			log("Achievement not found: " + id);

			return null;
		}

		public function unlockAchievement(id:String):IGameServicesModel
		{
			var ach:Achievement = getAchievementById(id);

			if (ach != null)
			{
				if (ach.state == Achievement.STATE_UNLOCKED)
				{
					log("Achievement already unlocked: " + ach.name);
				} else
				{
					log("Unlocking achievement: " + ach.name);
					
					Games.achievements.unlock(id, false);
				}
			}
			
			return this;
		}

		public function unlockAchievementList(idList:Vector.<String>):IGameServicesModel
		{
			if (!_signedIn || !_initialized || _isPending) return this;

			for each (var id:String in idList)
			{
				unlockAchievement(id);
			}

			return this;
		}

		private function showUserInfo($account:GAccount):void
		{
			log("displayName: " + $account.displayName);
			log("email: " + $account.email);
			log("familyName: " + $account.familyName);
			log("givenName: " + $account.givenName);
			log("id: " + $account.id);
			log("idToken: " + $account.idToken);
			log("photoUrl: " + $account.photoUrl);
			for (var i:int = 0; i < $account.scopes.length; i++)
			{
				log("\t" + $account.scopes[i]);
			}
			log("serverAuthCode: " + $account.serverAuthCode);

			_email = $account.email;
			_userId = $account.id;
			_serverAuthCode = $account.serverAuthCode;
		}

		private function onRequestFailure(event:GSignInEvents):void
		{
			log("onRequestFailure");
		}

		private function onRequestSuccess(event:GSignInEvents):void
		{
			log("onRequestSuccess");
		}

		private function onRevokeAccessFailure(event:GSignInEvents):void
		{
			log("onRevokeAccessFailure");
		}

		private function onRevokeAccessSuccess(event:GSignInEvents):void
		{
			log("onRevokeAccessSuccess");
		}

		private function onSignOutFailure(event:GSignInEvents):void
		{
			log("onSignOutFailure");

			_isPending = false;

			dispatchMessage(GameServicesModelMessage.SIGN_OUT_FAIL, null, true);
		}

		private function onSignOutSuccess(event:GSignInEvents):void
		{
			log("onSignOutSuccess");

			_isPending = false;

			dispatchMessage(GameServicesModelMessage.SIGN_OUT_SUCCESS, null, true);
		}

		private function onSignInFailure(event:GSignInEvents):void
		{
			/*
			 check the meaning of failure code here:
			 https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes
			 https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
			 */
			// if silent signin can't happen, it means that this is the first time that user is using the app
			// it may also mean that the user has signed out or revoked access the last time she has been using the app.
			// in such cases, you must create a signin button and when that is clicked, you must call:
			// GSignIn.signin();

			failed();
		}

		private function failed():void
		{
			try
			{
				Games.dismiss();
			} catch (e:Error)
			{
			}

			_isPending = false;

			log("Sign in failed");

			_signedIn = false;
			_userId = null;
			_nickname = null;

			_errorType = "Error";
			_errorReason = "Sign in failed";

			dispatchMessage(GameServicesModelMessage.SIGN_IN_FAIL, null, true);
		}

		private function onSignInSuccess(event:GSignInEvents):void
		{
			showUserInfo(event.account);

			signInSuccess();
		}

		private function signInSuccess():void
		{
			_isPending = false;

			log("Sign in signInSuccess");
			_signedIn = true;

			Games.init();

			if(!Games.listener.hasEventListener(GamesEvents.CONNECT_SUCCESS))
			{
				Games.listener.addEventListener(GamesEvents.CONNECT_SUCCESS, onConnectSuccess);
				Games.listener.addEventListener(GamesEvents.CONNECT_FAILURE, onConnectFailure);
				Games.listener.addEventListener(GamesEvents.ACHIEVEMENT_LOAD_RESULT, onAchievementsLoadResult);

				// There's no need to add this listener, it just shows you some more information about
				// how activities inside the ANE are doing.
				Games.listener.addEventListener(GamesEvents.ACTIVITY_RESULT_CODES, onActivityResultCodes);
			}
		}

		private function onAchievementsLoadResult(event:GamesEvents):void
		{
			if(event.status == Games.SUCCESS)
			{
				achievementList = event.achievements;

				log("Number of loaded achievements: " + event.achievements.length);

				for (var i:int = 0; i < event.achievements.length; i++)
				{
					var achievement:Achievement = event.achievements[i];
					log("\t id =", achievement.id);
					log("\t name =", achievement.name);
					log("\t description =", achievement.description);
					log("\t state =", achievement.state); // Achievement.STATE_UNLOCKED, Achievement.STATE_REVEALED, Achievement.STATE_HIDDEN
					log("\t type =", achievement.type); // Achievement.TYPE_STANDARD, Achievement.TYPE_INCREMENTAL
					log("\t xpValue =", achievement.xpValue);
					log("\t lastUpdatedTimestamp =", achievement.lastUpdatedTimestamp);

					if (achievement.type == Achievement.TYPE_INCREMENTAL)
					{
						log("\t currentSteps =", achievement.currentSteps);
						log("\t totalSteps =", achievement.totalSteps);
					}

					/*achievement.loadRevealedImage(false, function ($achievement:Achievement, $image:File):void
					{
						if($image)
						{
							log("onRevealedImageLoaded: " + $image.nativePath);
							log("RevealedImage.size: " + $image.size);
						}
						else
						{
							log("RevealedImage NOT AVAILABLE!")
						}
					});*/
				}

				dispatchMessage(GameServicesModelMessage.SIGN_IN_SUCCESS, null, true);
			} else 
			if(event.status == Games.FAILURE)
			{
				log("onAchievementsLoadResult failure: " + event.msg);

				failed();
			}
		}

		private function onActivityResultCodes(event:GamesEvents):void
		{
			// https://developers.google.com/android/reference/com/google/android/gms/games/GamesActivityResultCodes
			log("onActivityResultCodes: " + event.status);
		}

		private function onConnectFailure(event:GamesEvents):void
		{
			log("onConnectFailure: " + event.msg);

			failed();
		}

		private function onConnectSuccess(event:GamesEvents):void
		{
			log("displayName: " + event.player.displayName);
			log("id: " + event.player.id);
			log("lastPlayedTimestamp: " + event.player.lastPlayedTimestamp);
			log("title: " + event.player.title);
			log("retrievedTimestamp: " + event.player.retrievedTimestamp);
			log("hasHiResImage: " + event.player.hasHiResImage);
			log("hasIconImage: " + event.player.hasIconImage);

			if(event.player.levelInfo)
			{
				log("levelInfo.currentXpTotal: " + event.player.levelInfo.currentXpTotal);
				log("levelInfo.isMaxLevel: " + event.player.levelInfo.isMaxLevel);
				log("levelInfo.lastLevelUpTimestamp: " + event.player.levelInfo.lastLevelUpTimestamp);

				log("levelInfo.currentLevel.levelNumber: " + event.player.levelInfo.currentLevel.levelNumber);
				log("levelInfo.currentLevel.maxXp: " + event.player.levelInfo.currentLevel.maxXp);
				log("levelInfo.currentLevel.minXp: " + event.player.levelInfo.currentLevel.minXp);

				log("levelInfo.nextLevel.levelNumber: " + event.player.levelInfo.nextLevel.levelNumber);
				log("levelInfo.nextLevel.maxXp: " + event.player.levelInfo.nextLevel.maxXp);
				log("levelInfo.nextLevel.minXp: " + event.player.levelInfo.nextLevel.minXp);
			}

			_nickname = event.player.displayName;

			loadAchievements();
		}

		private function loadAchievements():void
		{
			Games.achievements.load(true);
		}

		private function onSilentSignInFailure(event:GSignInEvents):void
		{
			/*
			 check the meaning of failure code here:
			 https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes
			 https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
			 */
			log("onSilentSignInFailure: " + event.msg);

			// if silent signin can't happen, it means that this is the first time that user is using the app
			// it may also mean that the user has signed out or revoked access the last time she has been using the app.
			// in such cases, you must create a signin button and when that is clicked, you must call:
			// GSignIn.signin();

			log("Login manually!");
			GSignIn.signin();
		}

		private function onSilentSignInSuccess(event:GSignInEvents):void
		{
			showUserInfo(event.account);

			signInSuccess();
		}

		public function signIn():IGameServicesModel
		{
			if (_signedIn || !_initialized || _isPending) return this;

			// check if user is already logged-in or not
			var account:GAccount = GSignIn.signedInAccount;
			if (account && _serverAuthCode != null)
			{
				showUserInfo(account);

				signInSuccess();
			} else
			{
				_isPending = true;
				// You should first check if user can signin silently, if she can't, use the GSignIn.signin() method
				GSignIn.silentSignIn();
			}

			return this;
		}

		public function signOut(silent:Boolean = false):IGameServicesModel
		{
			if (!_initialized || _isPending || !_signedIn) return this;

			_isPending = true;

			_signedIn = false;
			_userId = null;
			_nickname = null;
			_email = null;
			_serverAuthCode = null;

			dispatchMessage(GameServicesModelMessage.SIGN_OUT_STARTED, null, true);

			try
			{
				Games.dismiss();
			} catch (e:Error)
			{
			}

			if (!silent && GSignIn.signedInAccount)
			{
				GSignIn.signOut();
			} else
			{
				onSignOutSuccess(null);
			}

			return this;
		}

		public function get isPending():Boolean
		{
			return false;
		}

		public function get initialized():Boolean
		{
			return _initialized;
		}

		public function get signedIn():Boolean
		{
			return _signedIn;
		}

		public function get userId():String
		{
			return _userId;
		}

		public function get nickname():String
		{
			return _nickname;
		}

		public function get errorType():String
		{
			return _errorType;
		}

		public function get errorReason():String
		{
			return _errorReason;
		}

		public function get email():String
		{
			return _email;
		}

		public function get enabled():Boolean
		{
			return _enabled;
		}

		public function get serverAuthCode():String
		{
			return _serverAuthCode;
		}
	}
}
```

## Steps to Reproduce ##
Nothing happens when I try to load achievements. In android logs I see current exception.
Dependencies are the latest.
```
10-04 12:36:09.160	3659	24028	W	AppOps	Bad call: specified package com.google.android.play.games under uid 11476 but it is really 10133
10-04 12:36:09.160	3659	24028	W	AppOps	java.lang.RuntimeException: here
10-04 12:36:09.160	3659	24028	W	AppOps		at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1356)
10-04 12:36:09.160	3659	24028	W	AppOps		at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1035)
10-04 12:36:09.160	3659	24028	W	AppOps		at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
10-04 12:36:09.160	3659	24028	W	AppOps		at android.os.Binder.execTransact(Binder.java:573)
10-04 12:36:09.162	3659	4582	W	AppOps	Bad call: specified package com.google.android.play.games under uid 11476 but it is really 10133
10-04 12:36:09.162	3659	4582	W	AppOps	java.lang.RuntimeException: here
10-04 12:36:09.162	3659	4582	W	AppOps		at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1356)
10-04 12:36:09.162	3659	4582	W	AppOps		at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1035)
10-04 12:36:09.162	3659	4582	W	AppOps		at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
10-04 12:36:09.162	3659	4582	W	AppOps		at android.os.Binder.execTransact(Binder.java:573)
```

## Known Workarounds ##
No

**Comment by CrazyFlasher** [comment]
Sorry, I've added listener to wrong object.
Should be:
```actionscript
Games.achievements.addEventListener(GamesEvents.ACHIEVEMENT_LOAD_RESULT, onAchievementsLoadResult);
```
